version: '3.7'

networks:
  backend-network:
    driver: bridge

services:
  product-backend:
    image: "product-backend:1.0"
    container_name: "product-backend"
    ports:
    - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
        interval: 20s
        timeout: 5s
        retries: 5
        start_period: 10s
    networks:
      - "backend-network"
