// reference: https://www.baeldung.com/postman-keycloak-endpoints
GET {{server}}/auth/realms/{{realm}}/.well-known/openid-configuration

###

// GET in your browser:
http://172.21.0.1:8180/auth/realms/kong/protocol/openid-connect/auth?response_type=code&client_id=stock-webapp&redirect_uri=http://172.21.0.1:3000
http://auth.keycloak.local/auth/realms/kong/protocol/openid-connect/auth?response_type=code&client_id=stock-webapp&redirect_uri=http://stock.frontend.local
// put username: user
// put password: user

###

// Copy param code in URL browser
POST {{server}}/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&client_id={{publicClientId}}&redirect_uri={{redirectUri}}&code=<PUT YOUR CODE>

###

// user info
GET {{server}}/auth/realms/{{realm}}/protocol/openid-connect/userinfo
Authorization: Bearer <PUT YOUR TOKEN>

###

//Introspect
POST {{server}}/auth/realms/{{realm}}/protocol/openid-connect/token/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{confidentialBasicAuthorization}}

token=<PUT YOUR TOKEN>

###
